================================================================================
JobID = 11141566
User = aicha.hajiali, Account = all
Partition = gpu, Nodelist = dge013
================================================================================
Lmod has detected the following error: The following module(s) are unknown:
"cuda11.1"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "cuda11.1"

Also make sure that all modulefiles written in TCL start with the string
#%Module



2022-02-06 12:42:42.771040: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/sw/rev/21.12/haswell/gcc-9.3.0/anaconda3-2021.05-e3srav/lib
2022-02-06 12:42:42.771113: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
pipeline start 21938276.032526337
finished loading packages 61.18086425587535
reading files and compiling image into dict of 4D images
getting info from /home/mpg08/aicha.hajiali/TLI_project/TLI_data/preprocessed/2021/211104/steps/postshift/general_pipeline_info_1.txt
32 lines found in txt_file with : as the delimiter
channel defined for similarity_check not recognized, so ch_0 used
{'script_run': 'general_pipline_4D.py', 'purpose': 'preprocessing session 211104 with pipeline from 220205', 'path_to_data': '/home/mpg08/aicha.hajiali/TLI_project/TLI_data/preprocessed/2021/211104/steps/all/', 'save_path': '/home/mpg08/aicha.hajiali/TLI_project/TLI_data/preprocessed/2021/211104/steps/postshift/', 'model_path': '/home/mpg08/aicha.hajiali/TLI_project/preprocessing/n2v/models/', 'output_name': '211104_brain1.2_LP40_P36', 'group': 'PhaseCorr', 'ch_names': ['GFP', 'red'], 'reg_subset': (0, 60, 325, 600, 300, 650), 'steps': ['ants', 'postshift'], 'rotat_O': 6.0, 'Flip': False, 'xy_pixel': 0.0764616, 'z_pixel': 0.4, 'clipLimit': 1.0, 'kernel_size': (45, 45), 'model_name': 'n2v_3D_v6', 'reference_last': False, 'ants_ref_no': 1.0, 'ref_reset': 50.0, 'save_pre_shift': True, 'sigma': 5.0, 'drift_corr': ['Rigid', 'Affine', 'SyNRA'], 'metric': ['meansquares', 'mattes', 'CC'], 'grad_step': 0.2, 'flow_sigma': 3.0, 'total_sigma': 0.0, 'aff_sampling': 32.0, 'reg_iterations': (240, 80, 20), 'aff_iterations': (3000, 1200, 1200, 60), 'aff_shrink_factors': (6, 4, 2, 1), 'aff_smoothing_sigmas': (3, 2, 1, 0), 'check_ch': 'GFP', 'aff_random_sampling_rate': 0.2, 'syn_sampling': 32, 'ants_ref_st': 0}
reading_text runtime 0.0022964589297771454
finished reading txt file 0.006036926060914993
files_list runtime 0.0027030855417251587
the first 5 files (including ref) are ['/home/mpg08/aicha.hajiali/TLI_project/TLI_data/preprocessed/2021/211104/steps/all/PhaseCorr_GFP_211104_brain1.2_LP40_P36.tif', '/home/mpg08/aicha.hajiali/TLI_project/TLI_data/preprocessed/2021/211104/steps/all/PhaseCorr_red_211104_brain1.2_LP40_P36.tif']
Traceback (most recent call last):
  File "/home/mpg08/aicha.hajiali/TLI_project/preprocessing/pipeline/scripts/general_pipeline_4D.py", line 1074, in <module>
    main()
  File "/home/mpg08/aicha.hajiali/TLI_project/preprocessing/pipeline/scripts/general_pipeline_4D.py", line 869, in main
    image_4D = {ch:io.imread(files_list[ind]) for ind, ch in enumerate(temp)} 
  File "/home/mpg08/aicha.hajiali/TLI_project/preprocessing/pipeline/scripts/general_pipeline_4D.py", line 869, in <dictcomp>
    image_4D = {ch:io.imread(files_list[ind]) for ind, ch in enumerate(temp)} 
  File "/usr/users/aicha.hajiali/.local/lib/python3.8/site-packages/skimage/io/_io.py", line 48, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/usr/users/aicha.hajiali/.local/lib/python3.8/site-packages/skimage/io/manage_plugins.py", line 207, in call_plugin
    return func(*args, **kwargs)
  File "/usr/users/aicha.hajiali/.local/lib/python3.8/site-packages/skimage/io/_plugins/tifffile_plugin.py", line 30, in imread
    return tifffile_imread(fname, **kwargs)
  File "/usr/users/aicha.hajiali/.conda/envs/preprocessing/lib/python3.8/site-packages/tifffile/tifffile.py", line 894, in imread
    return tif.asarray(**kwargs)
  File "/usr/users/aicha.hajiali/.conda/envs/preprocessing/lib/python3.8/site-packages/tifffile/tifffile.py", line 3370, in asarray
    result = self.filehandle.read_array(
  File "/usr/users/aicha.hajiali/.conda/envs/preprocessing/lib/python3.8/site-packages/tifffile/tifffile.py", line 10601, in read_array
    raise ValueError(f'failed to read {nbytes} bytes, got {n}')
ValueError: failed to read 15864954880 bytes, got 8588873328
python died with exit status 1
============ Job Information ===================================================
Submitted: 2022-02-06T12:41:50
Started: 2022-02-06T12:42:10
Ended: 2022-02-06T12:44:56
Elapsed: 3 min, Limit: 2820 min, Difference: 2817 min
CPUs: 24, Nodes: 1
============= ProfiT-HPC =======================================================
To generate the ProfiT-HPC text report, run the following command
profit-hpc 11141566
================================================================================
